// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc2kLOdEOstXudOze_bRnA9z1kaXm642s',
    appId: '1:1098219728573:web:f8dd65f5e0ab02927691d4',
    messagingSenderId: '1098219728573',
    projectId: 'bdcrudropa',
    authDomain: 'bdcrudropa.firebaseapp.com',
    storageBucket: 'bdcrudropa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAprwc8lCrTdxSDfWyYpsI9teo4bcU_RaY',
    appId: '1:1098219728573:android:87ae9b6771ff69cf7691d4',
    messagingSenderId: '1098219728573',
    projectId: 'bdcrudropa',
    storageBucket: 'bdcrudropa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8CE4K5NMOf-RCb8tFsBtADqcTXd8sxGM',
    appId: '1:1098219728573:ios:e29d4ddd9fc27b8b7691d4',
    messagingSenderId: '1098219728573',
    projectId: 'bdcrudropa',
    storageBucket: 'bdcrudropa.firebasestorage.app',
    iosBundleId: 'com.example.urbaflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8CE4K5NMOf-RCb8tFsBtADqcTXd8sxGM',
    appId: '1:1098219728573:ios:e29d4ddd9fc27b8b7691d4',
    messagingSenderId: '1098219728573',
    projectId: 'bdcrudropa',
    storageBucket: 'bdcrudropa.firebasestorage.app',
    iosBundleId: 'com.example.urbaflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc2kLOdEOstXudOze_bRnA9z1kaXm642s',
    appId: '1:1098219728573:web:b2274435ff2cb6647691d4',
    messagingSenderId: '1098219728573',
    projectId: 'bdcrudropa',
    authDomain: 'bdcrudropa.firebaseapp.com',
    storageBucket: 'bdcrudropa.firebasestorage.app',
  );
}
